In [3]:
# to handle  data retrieval
import urllib3
from urllib3 import request
# to handle certificate verification
import certifi
# to manage json data
import json
# for pandas dataframes
import pandas as pd
# uncomment below if installation needed (not necessary in Colab)
#!pip install certifi

In [5]:
# get data from the API

http = urllib3.PoolManager(
       cert_reqs='CERT_REQUIRED',
       ca_certs=certifi.where())
url = 'https://minio.dev.digitalservices.syr.edu/data/public/covid/syr-stats.json'
r = http.request('GET', url)
r.status

200

In [10]:
df = pd.read_json(r.data)
df.head(10)

,ActiveCases,ActiveCasesOutsideCNY,DateRecorded,NewEmployeePositives,NewEmployeePositivesOutsideCNY,NewStudentPositives,NewStudentPositivesOutsideCNY,NotesSection,NumberOfCases,NumberOfTests,PositveTests14Day,PositveTests14DayLabel,RecoveredCases,StudentsInQuarantine,TestAdministeredCampus10Day,TotalConfirmedCases,created_at,id,updated_at
0,4,0,2020-10-03,0,0,1,0,For information about COVID-19 in the City of ...,0,56657,5.0,Positive Tests Within 14-Day Period (Sep 26. -...,93,131,10057,-1,2020-10-03 17:45:38.989,37,2020-10-03 17:58:09.944
1,9,0,2020-10-05,0,0,5,0,For information about COVID-19 in the City of ...,0,57154,11.0,Positive Tests Within 14-Day Period (Sep 26. -...,94,40,8149,4,2020-10-05 17:35:37.201,39,2020-10-05 17:35:37.213
2,86,1,2020-10-10,0,0,10,0,"Syracuse University continues to trace, test a...",0,63737,10.0,Positive Tests Within 14-Day Period (Oct 10. -...,95,209,11080,10,2020-10-10 18:01:43.359,44,2020-10-10 18:01:43.372
3,25,0,2020-10-06,0,0,16,0,UPDATE: [As communicated earlier today](https...,0,58609,27.0,Positive Tests Within 14-Day Period (Sep 26. -...,94,62,8793,16,2020-10-06 16:58:46.766,40,2020-10-06 23:04:22.475
4,0,0,2020-08-06,0,0,0,0,None,0,0,NaN,None,0,0,0,0,2020-08-06 14:36:03.284,7,2020-08-18 16:22:48.381
5,45,0,2020-10-07,0,0,20,0,"Syracuse University continues to trace, test a...",0,60625,47.0,Positive Tests Within 14-Day Period (Sep 26. -...,94,134,10788,20,2020-10-07 17:55:20.456,41,2020-10-07 18:06:16.823
6,65,0,2020-10-08,0,0,20,0,"Syracuse University continues to trace, test a...",0,61368,67.0,Positive Tests Within 14-Day Period (Sep 26. -...,94,164,11232,20,2020-10-08 17:37:27.281,42,2020-10-08 17:37:27.293
7,5,8,2020-08-18,0,0,2,3,None,0,6194,NaN,None,10,10,0,5,2020-08-18 17:54:06.442,11,2020-08-18 17:54:20.473
8,3,5,2020-08-11,0,0,3,5,None,8,1344,NaN,None,5,0,0,8,2020-08-11 20:04:31.720,10,2020-08-18 17:54:26.390
9,76,1,2020-10-09,0,0,12,1,"Syracuse University continues to trace, test a...",0,62740,80.0,Positive Tests Within 14-Day Period (Sep 26. -...,95,191,10808,12,2020-10-09 19:55:02.319,43,2020-10-09 20:38:00.649